### ISSUE TITLE
worker通过rpc提交任务给master

### ISSUE THREAD

**Issue by xubigshu** [Masutangu/Elric#1]
但是我看了你配置settings.py中的RPC_CONFIG并没有其余任何地方调用呢？

**Comment by Masutangu** [comment]
后来把rpc去掉了，和任务下发整合在一起。请查看这个改动：https://github.com/Masutangu/Elric/commit/1594916f27a4ecf80e611aea6eb681c3b66a6fc8
之后我将整理一篇最新的文档，感谢反馈^ ^
